# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapgen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.creationBar = QtWidgets.QProgressBar(self.centralwidget)
        self.creationBar.setProperty("value", 0)
        self.creationBar.setInvertedAppearance(False)
        self.creationBar.setObjectName("creationBar")
        self.gridLayout_5.addWidget(self.creationBar, 1, 0, 1, 2)
        self.MainImage = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainImage.sizePolicy().hasHeightForWidth())
        self.MainImage.setSizePolicy(sizePolicy)
        self.MainImage.setObjectName("MainImage")
        self.gridLayout_5.addWidget(self.MainImage, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.heightLabel = QtWidgets.QLabel(self.centralwidget)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.inputHeight = QtWidgets.QSpinBox(self.centralwidget)
        self.inputHeight.setMinimum(1)
        self.inputHeight.setMaximum(1500)
        self.inputHeight.setSingleStep(100)
        self.inputHeight.setProperty("value", 200)
        self.inputHeight.setObjectName("inputHeight")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputHeight)
        self.lengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lengthLabel)
        self.inputLength = QtWidgets.QSpinBox(self.centralwidget)
        self.inputLength.setMinimum(1)
        self.inputLength.setMaximum(1500)
        self.inputLength.setSingleStep(100)
        self.inputLength.setProperty("value", 200)
        self.inputLength.setObjectName("inputLength")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputLength)
        self.algorithmLabel = QtWidgets.QLabel(self.centralwidget)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.algorithmLabel)
        self.inputAlgorithm = QtWidgets.QComboBox(self.centralwidget)
        self.inputAlgorithm.setObjectName("inputAlgorithm")
        self.inputAlgorithm.addItem("")
        self.inputAlgorithm.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputAlgorithm)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generateButton.setCheckable(False)
        self.generateButton.setObjectName("generateButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.generateButton)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.generateButton.clicked.connect(MainWindow.generateButton)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heightLabel.setText(_translate("MainWindow", "height"))
        self.lengthLabel.setText(_translate("MainWindow", "Length"))
        self.algorithmLabel.setText(_translate("MainWindow", "Algorithm"))
        self.inputAlgorithm.setItemText(0, _translate("MainWindow", "Simplex"))
        self.inputAlgorithm.setItemText(1, _translate("MainWindow", "Voronoi"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))

